name: run-tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  package-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.1, 8.2, 8.3]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, bcmath, pdo, pdo_mysql
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Validate composer.json
        run: |
          # Validate composer.json with warnings allowed
          composer validate || echo "⚠️ Composer validation completed with warnings"
          
          # Check if composer.json is syntactically valid
          composer validate --no-check-all --no-check-publish || {
            echo "❌ Critical composer.json validation failed"
            exit 1
          }
          
          echo "✅ Composer.json validation passed"

      - name: Check PHP syntax
        run: find src -name "*.php" -exec php -l {} \;

      - name: Run PHPUnit tests (if tests exist)
        run: |
          if [ -d "tests" ]; then
            vendor/bin/phpunit
          else
            echo "No tests directory found, skipping tests"
          fi

  laravel-integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # PHP 8.1 with Laravel 9, 10, 11
          - php-version: 8.1
            laravel-version: "^9.0"
          - php-version: 8.1
            laravel-version: "^10.0"
          - php-version: 8.1
            laravel-version: "^11.0"
          # PHP 8.2 with Laravel 10, 11, 12
          - php-version: 8.2
            laravel-version: "^10.0"
          - php-version: 8.2
            laravel-version: "^11.0"
          - php-version: 8.2
            laravel-version: "^12.0"
          # PHP 8.3 with Laravel 11, 12
          - php-version: 8.3
            laravel-version: "^11.0"
          - php-version: 8.3
            laravel-version: "^12.0"

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, bcmath, pdo, pdo_sqlite
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-laravel-${{ matrix.laravel-version }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-laravel-${{ matrix.laravel-version }}-php-${{ matrix.php-version }}-
            ${{ runner.os }}-laravel-${{ matrix.laravel-version }}-

      - name: Create Laravel project
        run: |
          # Install Laravel with specific version
          composer create-project laravel/laravel:${{ matrix.laravel-version }} laravel-app --prefer-dist --no-interaction

      - name: Install package into Laravel
        run: |
          cd laravel-app
          # Add local repository pointing to parent directory
          composer config repositories.local '{"type": "path", "url": "../", "options": {"symlink": false}}'
          # Show current Laravel version for debugging
          composer show laravel/framework | head -5
          # Install our package
          composer require ngodingskuyy/laravel-module-generator:@dev --no-interaction

      - name: Setup Laravel environment
        run: |
          cd laravel-app
          cp .env.example .env
          php artisan key:generate
          # Use SQLite for testing
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=:memory:/' .env
          touch database/database.sqlite

      - name: Verify package installation
        run: |
          cd laravel-app
          echo "=== Debugging Package Installation ==="
          # Check if composer installed the package
          composer show ngodingskuyy/laravel-module-generator || echo "Package not found in composer show"
          
          # Show all installed packages for debugging
          echo "=== Installed Packages ==="
          composer show | grep -E "(illuminate|spatie|ngodingskuyy)" || echo "No relevant packages found"
          
          # Clear and optimize Laravel
          php artisan config:clear
          php artisan cache:clear
          
          # Only cache config if package is properly installed
          if composer show ngodingskuyy/laravel-module-generator > /dev/null 2>&1; then
            php artisan config:cache
            echo "✅ Package is installed and config cached"
          else
            echo "❌ Package installation verification failed"
          fi

      - name: Test package installation
        run: |
          cd laravel-app
          # Check if package is actually installed before testing
          if ! composer show ngodingskuyy/laravel-module-generator > /dev/null 2>&1; then
            echo "❌ Package is not installed, skipping service provider tests"
            exit 0
          fi
          
          # Test if service provider is registered
          echo "=== Testing Service Provider Registration ==="
          php artisan about --only=providers | grep -i "LaravelModuleGenerator" && echo "✅ Service provider found" || echo "❌ Service provider not found"
          
          # Test if package commands are available
          echo "=== Testing Available Commands ==="
          php artisan list | grep -i "make:feature" && echo "✅ make:feature command is available" || echo "❌ make:feature command not found"

      - name: Test package functionality
        run: |
          cd laravel-app
          # Test if the command works without errors
          echo "=== Testing make:feature command ==="
          
          # First, check if command is registered
          if php artisan list | grep -q "make:feature"; then
            echo "✅ make:feature command found in artisan list"
            
            # Try to run the command
            if php artisan make:feature TestModule --force 2>&1; then
              echo "✅ make:feature command executed successfully"
            else
              echo "❌ make:feature command failed to execute"
              # Show any error logs
              php artisan make:feature TestModule --force -v || true
            fi
          else
            echo "❌ make:feature command not found in artisan list"
            echo "Available commands:"
            php artisan list | grep make || echo "No make commands found"
          fi
          
          # Check if files were created
          echo "=== Checking created files ==="
          echo "Controllers:"
          find app/Http/Controllers/ -name "*TestModule*" 2>/dev/null || echo "No controller files found"
          echo "Models:"
          find app/Models/ -name "*TestModule*" 2>/dev/null || echo "No model files found"
          echo "Migrations:"
          find database/migrations/ -name "*test_modules*" 2>/dev/null || echo "No migration files found"
          echo "Requests:"
          find app/Http/Requests/ -name "*TestModule*" 2>/dev/null || echo "No request files found"
          echo "Routes:"
          find routes/ -name "*TestModule*" -o -path "*/TestModules/*" 2>/dev/null || echo "No route modules found"
          
          # Show detailed error if command failed
          echo "=== Command help test ==="
          php artisan help make:feature || echo "Help command failed"
          
          # Try a simple command to verify it works
          echo "=== Basic command test ==="
          php artisan make:feature --help || echo "Command help failed"

      - name: Test Laravel application
        run: |
          cd laravel-app
          # Run basic Laravel tests to ensure nothing is broken
          php artisan test || echo "Laravel tests completed"
